# Generated by Django 5.0.6 on 2024-05-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('link_url', models.URLField()),
                ('display_duration', models.IntegerField()),
                ('transition_type', models.CharField(max_length=50)),
            ],
        ),
    ]
