# Generated by Django 5.0.6 on 2024-05-20 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_ad_image_url_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.AddField(
            model_name='ad',
            name='image_url',
            field=models.URLField(default=datetime.datetime(2024, 5, 20, 7, 27, 30, 104050, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
