# Generated by Django 5.0.6 on 2024-05-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_ad_image_ad_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='display_duration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='transition_type',
            field=models.IntegerField(),
        ),
    ]
