# Generated by Django 5.0.6 on 2024-05-20 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_display_duration_alter_ad_transition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='display_duration_end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 8, 12, 26, 562607, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
