# Generated by Django 5.0.6 on 2024-05-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_display_duration_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='display_duration_end_date',
        ),
    ]
