# Generated by Django 5.0.6 on 2024-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_rename_transition_type_ad_transition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link_url',
            field=models.URLField(max_length=1000),
        ),
    ]
