# Generated by Django 5.0.6 on 2024-05-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Register',
        ),
    ]
