# Generated by Django 5.0.6 on 2024-05-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_register_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='login_password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='login_username',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='fname',
            new_name='register_fname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='lname',
            new_name='register_lname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='register_password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='province',
            new_name='register_province',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='tel',
            new_name='register_tel',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='types',
            new_name='register_types',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='register_username',
        ),
    ]
