# Generated by Django 5.0.6 on 2024-05-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pro_mstr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro_mstr',
            old_name='pro_aumphur_code',
            new_name='pro_amphur_code',
        ),
        migrations.RenameField(
            model_name='pro_mstr',
            old_name='pro_aumphur_desc',
            new_name='pro_amphur_desc',
        ),
    ]
