# Generated by Django 5.0.6 on 2024-05-24 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_pro_amphur_code_pro_mstr_pro_aumphur_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_province_code', models.CharField(max_length=50)),
                ('add_tumbol_code', models.CharField(max_length=50)),
                ('add_tumbol_desc', models.CharField(max_length=100)),
                ('add_aumphur_code', models.CharField(max_length=50)),
                ('add_aumphur_desc', models.CharField(max_length=100)),
                ('add_code', models.CharField(max_length=30)),
                ('add_ctry_code', models.CharField(max_length=80)),
                ('add_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.register')),
            ],
        ),
    ]
