# Generated by Django 5.0.6 on 2024-05-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='add_province_desc',
            field=models.CharField(default='กรุงเทพมหานคร', max_length=100),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='add_user_id',
            field=models.CharField(max_length=50),
        ),
    ]
