# Generated by Django 5.0.6 on 2024-05-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_addresses_add_province_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='add_aumphur_code',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='add_ctry_code',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='add_province_code',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='add_tumbol_code',
        ),
    ]
