# Generated by Django 5.0.6 on 2024-05-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_addresses_add_aumphur_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='add_user_id',
            new_name='add_user',
        ),
    ]
