# Generated by Django 5.0.6 on 2024-05-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_add_user_id_addresses_add_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_mstr',
            name='pro_ctry_code',
        ),
    ]
