<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-27 03:22
=======
# Generated by Django 5.0.6 on 2024-05-27 03:13
>>>>>>> c4c8cea285bbf0224a8fad37a3d9fcbb1c431e25

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('users', '0018_remove_pro_mstr_pro_ctry_code'),
=======
    dependencies = [
        ("users", "0018_remove_pro_mstr_pro_ctry_code"),
>>>>>>> c4c8cea285bbf0224a8fad37a3d9fcbb1c431e25
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='pro_mstr',
            name='pro_country',
            field=models.CharField(default='TH', max_length=50),
=======
            model_name="pro_mstr",
            name="pro_country",
            field=models.CharField(default="TH", max_length=50),
>>>>>>> c4c8cea285bbf0224a8fad37a3d9fcbb1c431e25
        ),
    ]
