# Generated by Django 5.0.6 on 2024-05-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_remove_pro_mstr_pro_ctry_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pro_mstr",
            name="pro_country",
            field=models.CharField(default="TH", max_length=50),
        ),
    ]
