# Generated by Django 5.0.6 on 2024-05-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_pro_mstr_pro_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_mstr',
            name='pro_country',
        ),
        migrations.AddField(
            model_name='register',
            name='pro_aumphur_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pro_tumbol_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
