# Generated by Django 5.0.6 on 2024-05-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_pro_mstr_pro_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_mstr',
            name='pro_country',
        ),
    ]
