# Generated by Django 5.0.6 on 2024-05-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_pro_mstr_pro_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_mstr',
            name='pro_country',
            field=models.CharField(default='TH', max_length=50),
        ),
    ]
